# Generated by Django 3.2.12 on 2022-03-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('IdCountry', models.AutoField(primary_key=True, serialize=False)),
                ('NamCountry', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('IdHouse', models.AutoField(primary_key=True, serialize=False)),
                ('NamHouse', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Patronus',
            fields=[
                ('IdPatronus', models.AutoField(primary_key=True, serialize=False)),
                ('NamPatronus', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='biography',
            new_name='BiographyUser',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='modified',
            new_name='BirthUser',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='create',
            new_name='CreateUser',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='NamUser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AddField(
            model_name='profile',
            name='FirstNamUser',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='profile',
            name='LastNamUser',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='profile',
            name='ModifiedUser',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='CountryUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='HouseUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.house'),
        ),
        migrations.AddField(
            model_name='profile',
            name='PatronusUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patronus'),
        ),
    ]
